### ISSUE TITLE
Can't select system keyspace from keyspaces dropdown menu

### ISSUE THREAD

**Issue by yadkov** [grafana/astradb-datasource#41] opened 2022-11-08 14:31 UTC
While creating queries in builder mode from Grafana to Astradb I can't select the `system` keyspace from keyspaces dropdown menu.

When I switch to `code` mode I am able to select from the `system` keyspace.

Grafana version: 8.5.13
Astradb plugin version: 0.2.1

**Comment by ktw4071** [comment] 2022-11-08 14:54
Hi @yadkov,
Could you kindly upload UI screenshot that I can refer to? I will reproduce and fix it.
Thanks

**Comment by yadkov** [comment] 2022-11-09 08:35
This is the builder mode:
![image](https://user-images.githubusercontent.com/31875870/200778732-c244351e-a4d4-4a05-ad7e-1acb03a40aa6.png)

This is from the code mode:
![image](https://user-images.githubusercontent.com/31875870/200780129-e890509e-3f22-45fb-b022-95d297e7de10.png)

**Comment by yadkov** [comment] 2022-12-19 18:40
Any updates?

**Comment by ktw4071** [comment] 2022-12-19 20:38
Hello @yadkov, been working with other work. If it's not an urgent issue, I will pick up after finishing my current work.

**Comment by scottlepp** [comment] 2023-01-03 15:04
Hi @yadkov we intentionally filter out [system keyspaces](https://github.com/grafana/astradb-datasource/blob/7d98093c0a9126c43d81d90517cea3e1f3ce2b59/src/datasource.ts#L81) since these are system generated tables.  

Can you please help understand the use case of why you want to query these?  Thanks.

**Comment by yadkov** [comment] 2023-01-04 12:42
We would like to monitor the portions counts and their corresponding size. In order to do this we need the data which is stored in `size_estimates` in the system keyspace.

**Comment by scottlepp** [comment] 2023-01-04 19:31
@yadkov thanks for the update.  This seems like a more admin/advanced use case where the user knows the schema/metadata and how to write the CQL to get it, and has access to system tables.  

The query builder is really meant for users who are not familiar with CQL and shouldn't see system tables, but I suppose this can be managed with permissions in Cassandra.

With your scenario, the user would rather use the query builder ui rather than just writing the CQL?

**Comment by yadkov** [comment] 2023-01-05 14:10
CQL is preferred.

**Comment by scottlepp** [comment] 2023-01-05 16:20
Then it seems accessing system tables from the query builder ui is not necessary.  Going to close this.

**Closed by scottlepp** 2023-01-05 16:20 UTC

**Comment by yadkov** [comment] 2023-01-06 14:50
Maybe a comment comment in the documentation about the system keyspace could be useful.
